import Link from "next/link";

export default function ContactPage() {
  return <main className="min-h-screen overflow-hidden bg-[#030712] text-white selection:bg-violet-500/30">
    <section className="relative border-b border-white/[.07] bg-[radial-gradient(circle_at_80%_20%,rgba(37,99,235,.14),transparent_30%),radial-gradient(circle_at_15%_60%,rgba(124,58,237,.1),transparent_28%),#030712]">
      <div className="absolute inset-0 opacity-15" style={{backgroundImage:"linear-gradient(rgba(255,255,255,.05) 1px,transparent 1px),linear-gradient(90deg,rgba(255,255,255,.05) 1px,transparent 1px)",backgroundSize:"48px 48px"}}/>
      <div className="relative mx-auto max-w-6xl px-6 pb-20 pt-16 sm:pb-24 sm:pt-20"><Link href="/" className="text-sm text-slate-500 transition hover:text-cyan-300">← Home</Link>
        <div className="mt-14 max-w-4xl"><p className="text-[10px] font-medium uppercase tracking-[.25em] text-violet-300">Contact</p><h1 className="mt-4 text-4xl font-semibold tracking-tight sm:text-6xl">Let&apos;s build something <span className="bg-gradient-to-r from-cyan-200 to-violet-300 bg-clip-text text-transparent">useful.</span></h1><p className="mt-6 max-w-2xl text-lg leading-8 text-slate-400">Have a project, idea, or opportunity? I&apos;m open to building, learning, collaborating, and solving real problems.</p></div>
      </div>
    </section>

    <section className="mx-auto max-w-6xl px-6 py-16 sm:py-24"><div className="grid gap-8 lg:grid-cols-[1.25fr_.75fr]">
      <form action="mailto:Lesleimakori@gmail.com" method="post" encType="text/plain" className="rounded-3xl border border-cyan-300/15 bg-white/[.025] p-7 shadow-[0_30px_90px_rgba(37,99,235,.07)] sm:p-9"><div className="flex items-start justify-between gap-4"><div><p className="text-[9px] uppercase tracking-[.22em] text-cyan-300">Start a conversation</p><h2 className="mt-2 text-2xl font-semibold">Send a message</h2></div><span className="rounded-full border border-white/10 px-3 py-1.5 text-[9px] uppercase tracking-wider text-slate-600">Open to opportunities</span></div><div className="mt-8 space-y-5">
        <label className="block"><span className="text-sm font-medium text-slate-300">Name</span><input name="name" type="text" required placeholder="Your name" className="mt-2 w-full rounded-xl border border-white/10 bg-black/20 px-4 py-3 text-sm text-white outline-none transition placeholder:text-slate-700 focus:border-cyan-300/40" /></label>
        <label className="block"><span className="text-sm font-medium text-slate-300">Email</span><input name="email" type="email" required placeholder="you@example.com" className="mt-2 w-full rounded-xl border border-white/10 bg-black/20 px-4 py-3 text-sm text-white outline-none transition placeholder:text-slate-700 focus:border-cyan-300/40" /></label>
        <label className="block"><span className="text-sm font-medium text-slate-300">Message</span><textarea name="message" rows={7} required placeholder="Tell me what you&apos;re building or what you&apos;d like to discuss..." className="mt-2 w-full resize-none rounded-xl border border-white/10 bg-black/20 px-4 py-3 text-sm text-white outline-none transition placeholder:text-slate-700 focus:border-cyan-300/40" /></label>
        <button type="submit" className="group rounded-full bg-gradient-to-r from-cyan-400 to-violet-500 px-6 py-3 text-sm font-semibold text-slate-950 transition hover:scale-[1.02]">Send Message <span className="ml-1 transition group-hover:translate-x-1">→</span></button>
      </div><p className="mt-4 text-xs text-slate-600">Submitting opens your email client with the message addressed to me.</p></form>

      <aside className="space-y-5"><div className="rounded-3xl border border-white/10 bg-white/[.025] p-7"><p className="text-[9px] uppercase tracking-[.22em] text-violet-300">Direct</p><h2 className="mt-3 text-xl font-semibold">Prefer email?</h2><p className="mt-3 text-sm leading-7 text-slate-500">For opportunities, collaboration, project discussions, or anything else, email is the fastest way to reach me.</p><a href="mailto:Lesleimakori@gmail.com" className="mt-5 inline-block break-all text-sm font-medium text-cyan-300 transition hover:text-cyan-200">Lesleimakori@gmail.com</a></div>
        <div className="rounded-3xl border border-white/10 bg-white/[.025] p-7"><p className="text-[9px] uppercase tracking-[.22em] text-cyan-300">Elsewhere</p><h2 className="mt-3 text-xl font-semibold">Find me online</h2><div className="mt-5 flex flex-wrap gap-3"><a href="https://github.com/Leslei-254" target="_blank" rel="noreferrer" className="rounded-full border border-white/10 px-5 py-2.5 text-sm text-slate-300 transition hover:border-cyan-300/30 hover:text-white">GitHub ↗</a><a href="https://www.linkedin.com/in/leslei-makori-8989681b4/" target="_blank" rel="noreferrer" className="rounded-full border border-white/10 px-5 py-2.5 text-sm text-slate-300 transition hover:border-violet-300/30 hover:text-white">LinkedIn ↗</a></div></div>
        <div className="relative overflow-hidden rounded-3xl border border-violet-300/15 bg-[radial-gradient(circle_at_50%_20%,rgba(124,58,237,.22),transparent_55%),#070b17] p-7"><div className="absolute -right-10 -top-10 h-32 w-32 rounded-full bg-cyan-400/10 blur-3xl"/><p className="relative text-[9px] uppercase tracking-[.22em] text-slate-500">What I&apos;m looking for</p><div className="relative mt-5 space-y-3">{["Software engineering","AI engineering","Interesting projects","Opportunities to learn and build"].map((x,i)=><div key={x} className="flex items-center gap-3 text-sm text-slate-400"><span className="font-mono text-[9px] text-violet-400/70">0{i+1}</span>{x}</div>)}</div></div>
      </aside>
    </div></section>

    <section className="border-t border-white/[.07] bg-[#050a14]"><div className="mx-auto max-w-6xl px-6 py-16"><div className="flex flex-col gap-4 text-center sm:items-center"><p className="text-[10px] uppercase tracking-[.25em] text-slate-600">Keep building</p><p className="text-lg font-medium text-slate-300">Have an idea? Let&apos;s see where it can go.</p></div></div></section>
  </main>;
}
