import Link from "next/link";

const stack = ["JavaScript", "TypeScript", "AI"];
const pillars = ["AI interaction", "Content creation", "Digital services", "Software development", "Domains", "Hosting"];

export default function DokileAICaseStudy() {
  return <main className="min-h-screen overflow-hidden bg-[#030712] text-white selection:bg-violet-500/30">
    <section className="relative border-b border-white/[.07] bg-[radial-gradient(circle_at_80%_20%,rgba(124,58,237,.2),transparent_30%),radial-gradient(circle_at_15%_60%,rgba(37,99,235,.13),transparent_28%),#030712]">
      <div className="absolute inset-0 opacity-15" style={{backgroundImage:"linear-gradient(rgba(255,255,255,.05) 1px,transparent 1px),linear-gradient(90deg,rgba(255,255,255,.05) 1px,transparent 1px)",backgroundSize:"48px 48px"}}/>
      <div className="relative mx-auto max-w-6xl px-6 pb-20 pt-16 sm:pb-24 sm:pt-20"><Link href="/work" className="text-sm text-slate-500 transition hover:text-cyan-300">← Back to work</Link>
        <div className="mt-14 grid gap-12 lg:grid-cols-[1fr_.85fr] lg:items-center"><div><p className="text-[10px] uppercase tracking-[.25em] text-violet-300">03 · In development</p><h1 className="mt-4 text-4xl font-semibold tracking-tight sm:text-6xl">Dokile<br/><span className="bg-gradient-to-r from-cyan-200 to-violet-300 bg-clip-text text-transparent">AI.</span></h1><p className="mt-6 max-w-2xl text-lg leading-8 text-slate-400">An AI productivity and creativity platform bringing AI tools, content creation, digital services, software development, domains, and hosting together in one place.</p><div className="mt-7 flex flex-wrap gap-2">{stack.map(x=><span key={x} className="rounded-full border border-white/10 bg-white/[.03] px-3 py-1.5 text-[10px] text-slate-400">{x}</span>)}</div><a href="https://dokile.dokilewayne.workers.dev/" target="_blank" rel="noreferrer" className="mt-8 inline-flex rounded-full bg-gradient-to-r from-cyan-400 to-violet-500 px-6 py-3 text-sm font-semibold text-slate-950">Visit Dokile AI ↗</a></div>
          <div className="relative h-80 overflow-hidden rounded-3xl border border-violet-300/20 bg-[radial-gradient(circle_at_50%_45%,rgba(124,58,237,.3),transparent_38%),linear-gradient(135deg,#09091b,#100724)]"><div className="absolute inset-0 opacity-25" style={{backgroundImage:"linear-gradient(rgba(139,92,246,.15) 1px,transparent 1px),linear-gradient(90deg,rgba(139,92,246,.15) 1px,transparent 1px)",backgroundSize:"28px 28px"}}/><div className="relative flex h-full items-center justify-center"><div className="absolute h-48 w-48 rounded-full bg-violet-600/20 blur-3xl"/><div className="relative flex h-24 w-24 items-center justify-center rounded-3xl border border-violet-300/40 bg-white/[.08] text-2xl font-semibold shadow-[0_0_60px_rgba(168,85,247,.28)]">DA</div>{[["AI","left-8 top-12"],["CONTENT","right-7 top-10"],["SOFTWARE","left-7 bottom-12"],["DOMAINS","right-8 bottom-12"],["HOSTING","left-1/2 top-5"]].map(([label,pos])=><span key={label} className={`absolute ${pos} rounded-full border border-white/10 bg-white/[.04] px-3 py-1.5 text-[7px] uppercase tracking-widest text-white/55`}>{label}</span>)}</div></div>
        </div></div>
    </section>

    <section className="mx-auto max-w-6xl px-6 py-20 sm:py-24"><div className="grid gap-10 lg:grid-cols-[.7fr_1.3fr]"><div><p className="text-[10px] uppercase tracking-[.25em] text-cyan-300">The idea</p><h2 className="mt-3 text-3xl font-semibold">One platform for a bigger digital vision.</h2></div><p className="max-w-3xl text-lg leading-8 text-slate-400">I wanted to bring different digital services and solutions together in one place instead of having them separated across different platforms.</p></div><div className="mt-16 grid gap-4 md:grid-cols-2">{[["What I’m building","AI interaction, AI-assisted content creation, blogs and articles, website services, software development services, domain services, and hosting."],["My role","I’m building and developing Dokile AI, working across the website, its pages, features, and integrations."],["What exists now","The project includes foundations for different areas of the platform while development continues."],["The challenge","Connecting pages and troubleshooting the links between different parts of a growing platform has been one of the hardest parts."]].map(([t,d],i)=><div key={t} className="rounded-2xl border border-white/10 bg-white/[.025] p-7"><span className="font-mono text-[9px] text-violet-400/70">0{i+1}</span><h3 className="mt-4 text-xl font-semibold">{t}</h3><p className="mt-3 text-sm leading-7 text-slate-500">{d}</p></div>)}</div></section>

    <section className="border-y border-white/[.07] bg-[#050a14]"><div className="mx-auto max-w-6xl px-6 py-20 sm:py-24"><p className="text-[10px] uppercase tracking-[.25em] text-violet-300">The platform</p><h2 className="mt-3 text-3xl font-semibold">Six areas, one direction.</h2><div className="mt-10 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{pillars.map((item,i)=><div key={item} className="group rounded-2xl border border-white/10 bg-white/[.025] p-6 transition duration-300 hover:-translate-y-1 hover:border-violet-400/25"><span className="font-mono text-[9px] text-slate-600">0{i+1}</span><h3 className="mt-5 text-lg font-semibold">{item}</h3><div className="mt-5 h-px w-12 bg-gradient-to-r from-cyan-300 to-violet-500 transition group-hover:w-20"/></div>)}</div></div></section>

    <section className="mx-auto max-w-6xl px-6 py-20 sm:py-24"><div className="rounded-3xl border border-violet-300/15 bg-[radial-gradient(circle_at_80%_30%,rgba(124,58,237,.2),transparent_35%),#07101d] p-8 sm:p-12"><p className="text-[10px] uppercase tracking-[.25em] text-cyan-300">What I learned</p><h2 className="mt-3 text-3xl font-semibold sm:text-4xl">Large products take time.</h2><p className="mt-5 max-w-3xl leading-8 text-slate-400">This project taught me that building a larger product takes time, patience, and commitment. I’ve learned to keep working through problems, troubleshoot what isn’t working, and continue improving the project instead of expecting everything to work immediately.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/work" className="rounded-full border border-white/10 px-5 py-2.5 text-sm text-slate-300">← More projects</Link><a href="https://github.com/Leslei-254/dokile" target="_blank" rel="noreferrer" className="rounded-full border border-white/10 px-5 py-2.5 text-sm text-slate-300">View GitHub ↗</a><Link href="/contact" className="rounded-full bg-gradient-to-r from-cyan-400 to-violet-500 px-5 py-2.5 text-sm font-semibold text-slate-950">Discuss a project →</Link></div></div></section>

    <section className="border-t border-white/[.07] bg-[#050a14]"><div className="mx-auto max-w-6xl px-6 py-16"><div className="flex flex-col gap-4 text-center sm:items-center"><p className="text-[10px] uppercase tracking-[.25em] text-slate-600">Current status</p><p className="text-lg font-medium text-slate-300">Dokile AI is still in development — and that’s part of the story.</p></div></div></section>
  </main>;
}
