import Link from "next/link";

const projects = [
  { number: "01", status: "Ready to use", title: "LeadDesk Mini CRM", description: "A clean CRM for businesses to view, track, and manage customer form submissions.", href: "/work/leaddesk", tech: ["Next.js", "Prisma", "Neon"], type: "crm" },
  { number: "02", status: "Completed", title: "Polite Scraper", description: "A production-minded Node.js scraper that turns book pages into structured JSON.", href: "/work/polite-scraper", tech: ["Node.js", "Cheerio", "JSON"], type: "scraper" },
  { number: "03", status: "In development", title: "Dokile AI", description: "An AI platform bringing tools, content, software services, domains, and hosting together.", href: "/work/dokile-ai", tech: ["JavaScript", "TypeScript", "AI"], type: "ai" },
];

const skills = ["JavaScript", "TypeScript", "Next.js", "Node.js", "Prisma", "Neon", "AI tools"];

function ProjectGraphic({ type }: { type: string }) {
  if (type === "crm") return (
    <div className="relative h-64 overflow-hidden rounded-2xl border border-cyan-400/20 bg-[radial-gradient(circle_at_75%_25%,rgba(79,70,229,.32),transparent_35%),linear-gradient(135deg,#07101f,#090b18)] p-4 text-white shadow-[0_20px_60px_rgba(37,99,235,.15)] transition duration-500 group-hover:-translate-y-1 group-hover:shadow-[0_25px_70px_rgba(124,58,237,.22)]">
      <div className="absolute -right-16 -top-16 h-48 w-48 rounded-full bg-violet-600/15 blur-3xl" />
      <div className="relative rounded-xl border border-white/10 bg-[#0b1220]/90 p-3 shadow-2xl backdrop-blur"><div className="flex items-center gap-1.5 border-b border-white/10 pb-3"><span className="h-2 w-2 rounded-full bg-cyan-300" /><span className="h-2 w-2 rounded-full bg-violet-400" /><span className="ml-2 text-[9px] text-white/40">leaddesk / dashboard</span></div><div className="grid grid-cols-4 gap-2 py-3">{[["Leads","248","+18%"],["Progress","92","+12%"],["Converted","56","+25%"],["Revenue","$24.8K","+32%"]].map(([a,b,c]) => <div key={a} className="rounded-lg border border-white/10 bg-white/[.035] p-2"><p className="text-[7px] text-white/40">{a}</p><p className="mt-1 text-sm font-semibold">{b}</p><p className="text-[7px] text-cyan-300">{c}</p></div>)}</div><div className="grid grid-cols-[.8fr_1.2fr] gap-2"><div className="rounded-lg border border-white/10 bg-white/[.025] p-3"><p className="text-[8px] text-white/40">Recent leads</p>{["Jane Cooper","Cody Fisher","Ethan Howard"].map((x) => <div key={x} className="mt-2 flex items-center gap-2 text-[8px] text-white/60"><span className="h-4 w-4 rounded-full bg-gradient-to-br from-cyan-300 to-violet-500" />{x}</div>)}</div><div className="rounded-lg border border-white/10 bg-white/[.025] p-3"><p className="text-[8px] text-white/40">Pipeline overview</p><svg viewBox="0 0 220 70" className="mt-3 h-14 w-full"><path d="M0 58 C35 45 38 62 65 43 S95 50 115 30 S150 45 175 18 S200 30 220 6" fill="none" stroke="url(#g)" strokeWidth="2"/><defs><linearGradient id="g"><stop stopColor="#22d3ee"/><stop offset="1" stopColor="#a855f7"/></linearGradient></defs></svg></div></div></div>
      <span className="absolute bottom-4 left-5 text-[9px] uppercase tracking-[.2em] text-cyan-200/60">FORM → CRM → TRACK → COMPLETE</span>
    </div>
  );
  if (type === "scraper") return (
    <div className="relative h-64 overflow-hidden rounded-2xl border border-cyan-400/15 bg-[radial-gradient(circle_at_70%_30%,rgba(14,165,233,.18),transparent_38%),#07101c] p-5 text-white shadow-[0_20px_60px_rgba(6,182,212,.08)] transition duration-500 group-hover:-translate-y-1">
      <div className="absolute inset-0 opacity-25" style={{ backgroundImage: "linear-gradient(rgba(56,189,248,.12) 1px, transparent 1px),linear-gradient(90deg,rgba(56,189,248,.12) 1px,transparent 1px)", backgroundSize: "30px 30px" }} />
      <div className="relative mt-3 flex items-center justify-center gap-2"><div className="w-[31%] rounded-xl border border-white/10 bg-white/[.04] p-3 shadow-xl"><p className="text-[8px] text-cyan-200">WEB SOURCE</p><div className="mt-3 h-2 w-16 rounded bg-white/15" /><div className="mt-2 h-14 rounded-lg bg-white/[.05]" /><p className="mt-2 text-[7px] text-white/35">books.toscrape.com</p></div><span className="text-lg text-cyan-300/70">→</span><div className="w-[31%] rounded-xl border border-cyan-300/20 bg-white/[.04] p-3 shadow-xl"><p className="text-[8px] text-violet-200">PARSE + CLEAN</p><div className="mt-3 space-y-2 font-mono text-[7px] text-white/45"><div>title()</div><div>price()</div><div>rating()</div><div>normalize()</div></div></div><span className="text-lg text-violet-300/70">→</span><div className="w-[31%] rounded-xl border border-violet-300/20 bg-white/[.04] p-3 shadow-xl"><p className="text-[8px] text-cyan-200">STRUCTURED JSON</p><pre className="mt-3 text-[7px] leading-3 text-white/50">{`{\n  title: "...",\n  price: "£...",\n  stock: true\n}`}</pre></div></div>
      <div className="absolute bottom-5 left-5 right-5 flex justify-between text-[9px] uppercase tracking-[.2em] text-white/40"><span>Node.js</span><span>Validation</span><span>JSON output</span></div>
    </div>
  );
  return (
    <div className="relative h-64 overflow-hidden rounded-2xl border border-violet-400/20 bg-[radial-gradient(circle_at_50%_45%,rgba(124,58,237,.32),transparent_35%),linear-gradient(135deg,#09091b,#100724)] text-white shadow-[0_20px_70px_rgba(124,58,237,.15)] transition duration-500 group-hover:-translate-y-1">
      <div className="absolute inset-0 opacity-30" style={{ backgroundImage: "linear-gradient(rgba(139,92,246,.14) 1px, transparent 1px),linear-gradient(90deg,rgba(139,92,246,.14) 1px,transparent 1px)", backgroundSize: "28px 28px" }} />
      <div className="relative flex h-full items-center justify-center"><div className="absolute h-40 w-40 rounded-full bg-violet-600/20 blur-3xl" /><div className="relative flex h-24 w-24 items-center justify-center rounded-3xl border border-violet-300/40 bg-white/[.08] text-2xl font-semibold shadow-[0_0_50px_rgba(168,85,247,.25)] backdrop-blur">DA</div>{[["AI", "left-8 top-10"],["CONTENT", "right-7 top-8"],["SOFTWARE", "left-6 bottom-9"],["DOMAINS", "right-8 bottom-10"],["HOSTING", "left-1/2 top-3"]].map(([label,pos]) => <span key={label} className={`absolute ${pos} rounded-full border border-white/10 bg-white/[.04] px-2.5 py-1 text-[7px] uppercase tracking-widest text-white/60 backdrop-blur`}>{label}</span>)}</div>
    </div>
  );
}

export default function Home() {
  return (
    <main className="min-h-screen overflow-hidden bg-[#030712] text-white selection:bg-violet-500/30">
      <section className="relative border-b border-white/[.07] bg-[radial-gradient(circle_at_75%_35%,rgba(37,99,235,.16),transparent_30%),radial-gradient(circle_at_95%_65%,rgba(124,58,237,.18),transparent_32%),#030712]">
        <div className="absolute inset-0 opacity-20" style={{ backgroundImage: "linear-gradient(rgba(255,255,255,.05) 1px,transparent 1px),linear-gradient(90deg,rgba(255,255,255,.05) 1px,transparent 1px)", backgroundSize: "48px 48px" }} />
        <div className="relative mx-auto max-w-7xl px-6 pb-20 pt-16 sm:pb-28 sm:pt-20">
          <div className="grid items-center gap-12 lg:grid-cols-[.88fr_1.12fr]">
            <div className="relative z-10">
              <div className="mb-6 inline-flex items-center gap-2 rounded-full border border-violet-400/25 bg-violet-500/[.07] px-3 py-1.5 text-[10px] font-medium uppercase tracking-[.2em] text-violet-200"><span className="h-1.5 w-1.5 rounded-full bg-cyan-300 shadow-[0_0_12px_rgba(103,232,249,.8)]" /> Backend AI Engineer</div>
              <h1 className="max-w-3xl text-6xl font-semibold leading-[.88] tracking-[-.055em] sm:text-8xl">LESLEI<br /><span className="bg-gradient-to-r from-white via-cyan-100 to-violet-300 bg-clip-text text-transparent">MAKORI</span></h1>
              <p className="mt-7 max-w-xl text-lg leading-8 text-slate-300">I build, troubleshoot, and ship <span className="text-cyan-300">AI-powered web applications</span> that solve real business problems.</p>
              <div className="mt-8 flex flex-wrap gap-3"><Link href="/work" className="rounded-full bg-gradient-to-r from-cyan-400 to-violet-500 px-6 py-3 text-sm font-semibold text-white shadow-[0_10px_35px_rgba(124,58,237,.28)] transition hover:-translate-y-0.5">View My Work →</Link><Link href="/about" className="rounded-full border border-white/20 bg-white/[.03] px-6 py-3 text-sm font-medium text-white transition hover:border-cyan-300/50 hover:bg-white/[.06]">About Me</Link></div>
              <div className="mt-12"><p className="text-[9px] uppercase tracking-[.25em] text-slate-500">Technologies I work with</p><div className="mt-4 flex flex-wrap gap-2">{skills.map((skill) => <span key={skill} className="rounded-lg border border-white/10 bg-white/[.03] px-3 py-2 text-xs text-slate-300">{skill}</span>)}</div></div>
            </div>
            <div className="relative min-h-[420px] lg:min-h-[500px]">
              <div className="absolute -right-20 top-12 h-80 w-80 rounded-full bg-violet-600/15 blur-3xl" /><div className="absolute right-0 top-24 h-72 w-72 rounded-full bg-cyan-500/10 blur-3xl" />
              <div className="absolute left-[8%] top-[4%] w-[48%] -rotate-3 rounded-xl border border-cyan-300/20 bg-[#07101c]/90 p-4 shadow-2xl backdrop-blur-xl"><div className="flex gap-1.5"><span className="h-2 w-2 rounded-full bg-red-400/70" /><span className="h-2 w-2 rounded-full bg-yellow-300/70" /><span className="h-2 w-2 rounded-full bg-green-300/70" /></div><pre className="mt-4 text-[9px] leading-5 text-slate-400"><span className="text-emerald-300">const</span> solution = <span className="text-violet-300">build</span>();{`\n`}solution.<span className="text-cyan-300">debug</span>();{`\n`}solution.<span className="text-violet-300">ship</span>();</pre></div>
              <div className="absolute right-[1%] top-[9%] w-[72%] rounded-2xl border border-blue-300/20 bg-[#08111f]/95 p-3 shadow-[0_30px_80px_rgba(37,99,235,.18)] backdrop-blur-xl"><div className="flex items-center justify-between border-b border-white/10 px-2 pb-3 text-[8px] text-white/45"><span>LeadDesk</span><span>Dashboard</span></div><div className="grid grid-cols-4 gap-2 py-3">{[["Leads","248"],["In Progress","92"],["Converted","56"],["Revenue","$24.8K"]].map(([a,b]) => <div key={a} className="rounded-lg border border-white/10 bg-white/[.03] p-2"><p className="text-[6px] text-white/35">{a}</p><p className="mt-1 text-sm font-semibold text-white">{b}</p></div>)}</div><div className="h-24 rounded-lg border border-white/10 bg-gradient-to-br from-white/[.04] to-violet-500/[.04] p-3"><p className="text-[7px] text-white/35">Pipeline overview</p><svg viewBox="0 0 300 80" className="mt-2 h-16 w-full"><path d="M0 62 C35 50 55 67 78 44 S120 58 148 30 S190 52 218 23 S260 32 300 8" fill="none" stroke="url(#heroLine)" strokeWidth="2"/><defs><linearGradient id="heroLine"><stop stopColor="#22d3ee"/><stop offset="1" stopColor="#a855f7"/></linearGradient></defs></svg></div></div>
              <div className="absolute bottom-[3%] left-[15%] w-[68%] rounded-2xl border border-violet-300/20 bg-[#080c19]/95 p-4 shadow-2xl backdrop-blur-xl"><div className="flex items-center justify-between"><span className="text-[8px] uppercase tracking-widest text-violet-200">Build pipeline</span><span className="text-[8px] text-white/35">IDEA → CODE → TEST → DEPLOY</span></div><div className="mt-4 flex items-center justify-between">{["IDEA","CODE","TEST","DEPLOY"].map((x,i) => <div key={x} className="flex items-center gap-2"><span className={`flex h-7 w-7 items-center justify-center rounded-full border ${i === 3 ? "border-cyan-300/50 bg-cyan-300/10 text-cyan-200" : "border-white/10 bg-white/[.03] text-white/50"} text-[7px]`}>{String(i+1).padStart(2,"0")}</span>{i < 3 && <span className="h-px w-5 bg-gradient-to-r from-cyan-400/40 to-violet-400/40" />}</div>)}</div></div>
              <div className="absolute bottom-[10%] right-[1%] rounded-xl border border-cyan-300/20 bg-[#08111c]/95 px-4 py-3 shadow-2xl backdrop-blur-xl"><p className="text-[7px] uppercase tracking-widest text-cyan-200/70">Polite Scraper</p><p className="mt-1 font-mono text-[8px] text-white/45">web → parse → validate → JSON</p></div>
            </div>
          </div>
        </div>
      </section>

      <section className="border-b border-white/[.07] bg-[#050a14]"><div className="mx-auto max-w-7xl px-6 py-4"><div className="flex flex-wrap items-center justify-center gap-x-10 gap-y-3 text-[9px] font-medium uppercase tracking-[.22em] text-slate-500"><span className="text-slate-300">JavaScript</span><span>TypeScript</span><span>Next.js</span><span>Node.js</span><span>Prisma</span><span>Neon</span><span>AI</span></div></div></section>

      <section className="mx-auto max-w-7xl px-6 py-20 sm:py-28"><div className="flex items-end justify-between gap-6"><div><p className="text-[10px] font-medium uppercase tracking-[.25em] text-violet-300">Selected Work</p><h2 className="mt-3 text-4xl font-semibold tracking-tight sm:text-5xl">Turning ideas into <span className="text-slate-500">real software.</span></h2></div><Link href="/work" className="hidden rounded-full border border-white/15 px-5 py-2.5 text-xs text-slate-300 hover:border-cyan-300/40 sm:block">View all projects →</Link></div><div className="mt-10 grid gap-6 lg:grid-cols-3">{projects.map((project) => <Link key={project.href} href={project.href} className="group rounded-2xl border border-white/10 bg-white/[.025] p-3 transition duration-500 hover:-translate-y-1 hover:border-violet-400/30 hover:bg-white/[.04]"><ProjectGraphic type={project.type} /><div className="px-2 pb-3 pt-5"><div className="flex items-center justify-between"><span className="text-[9px] font-medium uppercase tracking-[.18em] text-slate-500">{project.number} · {project.status}</span><span className="text-violet-300 opacity-0 transition group-hover:opacity-100">↗</span></div><h3 className="mt-3 text-xl font-semibold tracking-tight">{project.title}</h3><p className="mt-2 text-sm leading-6 text-slate-400">{project.description}</p><div className="mt-4 flex flex-wrap gap-2">{project.tech.map((tech) => <span key={tech} className="rounded-full border border-white/10 px-2.5 py-1 text-[9px] text-slate-500">{tech}</span>)}</div></div></Link>)}</div></section>

      <section className="border-y border-white/[.07] bg-[radial-gradient(circle_at_15%_50%,rgba(37,99,235,.13),transparent_28%),radial-gradient(circle_at_85%_50%,rgba(124,58,237,.14),transparent_28%),#050a14]"><div className="mx-auto grid max-w-7xl gap-14 px-6 py-20 sm:py-24 lg:grid-cols-[1fr_.9fr] lg:items-center"><div><p className="text-[10px] uppercase tracking-[.25em] text-cyan-300">How I work</p><h2 className="mt-4 max-w-xl text-4xl font-semibold tracking-tight sm:text-5xl">The hard part is troubleshooting.</h2><p className="mt-6 max-w-xl text-base leading-8 text-slate-400">Projects don&apos;t always work on the first attempt. I&apos;ve learned to approach problems with patience, persistence, and commitment—keep testing, keep learning, and keep fixing.</p></div><div className="grid grid-cols-2 overflow-hidden rounded-2xl border border-white/10 bg-white/[.02]">{[["01","Learn"],["02","Build"],["03","Troubleshoot"],["04","Ship"]].map(([n,label],i) => <div key={n} className={`p-7 ${i < 2 ? "border-b" : ""} ${i % 2 === 0 ? "border-r" : ""} border-white/10`}><span className="text-3xl font-semibold text-white">{n}</span><p className="mt-3 text-sm text-slate-500">{label}</p></div>)}</div></div></section>

      <section className="mx-auto max-w-7xl px-6 py-20 sm:py-24"><div className="rounded-3xl border border-white/10 bg-gradient-to-br from-white/[.04] to-violet-500/[.04] p-8 sm:p-12"><div className="flex flex-col gap-8 lg:flex-row lg:items-center lg:justify-between"><div><p className="text-[10px] uppercase tracking-[.25em] text-violet-300">Building toward what&apos;s next</p><h2 className="mt-3 text-3xl font-semibold tracking-tight sm:text-4xl">Becoming a stronger software + AI engineer.</h2><p className="mt-4 max-w-2xl text-sm leading-7 text-slate-400">I know enough to build. I&apos;m continuing to learn, troubleshoot, and build better.</p></div><div className="flex flex-wrap gap-3">{skills.slice(0,6).map((skill) => <span key={skill} className="rounded-full border border-white/10 bg-white/[.03] px-3 py-2 text-xs text-slate-400">{skill}</span>)}</div></div></div></section>

      <section className="border-t border-white/[.07]"><div className="mx-auto flex max-w-7xl flex-col gap-6 px-6 py-20 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-[10px] uppercase tracking-[.25em] text-slate-500">Have a project or idea?</p><h2 className="mt-3 text-3xl font-semibold tracking-tight sm:text-4xl">Let&apos;s build something useful.</h2></div><Link href="/contact" className="w-fit rounded-full bg-gradient-to-r from-cyan-400 to-violet-500 px-6 py-3 text-sm font-semibold text-white shadow-[0_10px_35px_rgba(124,58,237,.22)] transition hover:-translate-y-0.5">Let&apos;s Work Together →</Link></div></section>
    </main>
  );
}
