import Link from "next/link";

const projects = [
  { number: "01", status: "Ready to use", title: "LeadDesk Mini CRM", description: "A clean CRM for businesses to view, track, and manage customer form submissions.", href: "/work/leaddesk", tech: ["Next.js", "Prisma", "Neon"] },
  { number: "02", status: "Completed", title: "Polite Scraper", description: "A production-minded Node.js scraper that turns book pages into structured JSON.", href: "/work/polite-scraper", tech: ["Node.js", "Cheerio", "JSON"] },
  { number: "03", status: "In development", title: "Dokile AI", description: "An AI platform bringing tools, content, software services, domains, and hosting together.", href: "/work/dokile-ai", tech: ["JavaScript", "TypeScript", "AI"] },
];

const skills = ["JavaScript", "TypeScript", "Next.js", "Node.js", "Prisma", "Neon", "AI tools"];

function ProjectVisual({ index }: { index: number }) {
  if (index === 0) return (
    <div className="relative h-64 overflow-hidden rounded-2xl border border-cyan-300/15 bg-[radial-gradient(circle_at_75%_25%,rgba(124,58,237,.22),transparent_35%),#07101d] p-4 shadow-[0_24px_70px_rgba(34,211,238,.08)] transition duration-500 group-hover:-translate-y-1 group-hover:border-cyan-300/30">
      <div className="relative rounded-xl border border-white/10 bg-[#0b1322]/95 p-3 shadow-2xl">
        <div className="flex items-center gap-1.5 border-b border-white/10 pb-3"><span className="h-2 w-2 rounded-full bg-cyan-300" /><span className="h-2 w-2 rounded-full bg-violet-400" /><span className="ml-2 text-[9px] text-white/40">leaddesk / dashboard</span></div>
        <div className="grid grid-cols-4 gap-2 py-3">{[["Leads","248"],["Progress","92"],["Converted","56"],["Revenue","$24.8K"]].map(([a,b]) => <div key={a} className="rounded-lg border border-white/10 bg-white/[.035] p-2"><p className="text-[7px] text-white/35">{a}</p><p className="mt-1 text-sm font-semibold">{b}</p></div>)}</div>
        <div className="grid grid-cols-[.8fr_1.2fr] gap-2"><div className="rounded-lg border border-white/10 p-3"><p className="text-[8px] text-white/35">Recent leads</p>{["New enquiry","Follow up","Completed"].map((x) => <div key={x} className="mt-2 flex items-center gap-2 text-[8px] text-white/55"><span className="h-3 w-3 rounded-full bg-gradient-to-br from-cyan-300 to-violet-500" />{x}</div>)}</div><div className="rounded-lg border border-white/10 p-3"><p className="text-[8px] text-white/35">Pipeline</p><div className="mt-5 h-1 rounded-full bg-gradient-to-r from-cyan-300 via-blue-400 to-violet-500" /><div className="mt-3 h-1 w-3/4 rounded-full bg-white/10" /></div></div>
      </div>
      <span className="absolute bottom-4 left-5 text-[9px] uppercase tracking-[.2em] text-cyan-200/60">FORM → CRM → TRACK → COMPLETE</span>
    </div>
  );

  if (index === 1) return (
    <div className="relative h-64 overflow-hidden rounded-2xl border border-cyan-300/15 bg-[radial-gradient(circle_at_70%_30%,rgba(14,165,233,.18),transparent_40%),#07101c] p-5 shadow-[0_24px_70px_rgba(6,182,212,.08)] transition duration-500 group-hover:-translate-y-1 group-hover:border-violet-300/30">
      <div className="absolute inset-0 opacity-20" style={{ backgroundImage: "linear-gradient(rgba(56,189,248,.16) 1px,transparent 1px),linear-gradient(90deg,rgba(56,189,248,.16) 1px,transparent 1px)", backgroundSize: "30px 30px" }} />
      <div className="relative mt-5 flex items-center justify-center gap-2"><div className="w-[30%] rounded-xl border border-white/10 bg-white/[.04] p-3"><p className="text-[8px] text-cyan-200">WEB</p><div className="mt-3 h-12 rounded-lg bg-white/[.06]" /><p className="mt-2 text-[7px] text-white/30">book pages</p></div><span className="text-cyan-300">→</span><div className="w-[30%] rounded-xl border border-cyan-300/20 bg-white/[.04] p-3"><p className="text-[8px] text-violet-200">PARSE</p><div className="mt-3 space-y-2 font-mono text-[7px] text-white/40"><div>title()</div><div>price()</div><div>validate()</div></div></div><span className="text-violet-300">→</span><div className="w-[30%] rounded-xl border border-violet-300/20 bg-white/[.04] p-3"><p className="text-[8px] text-cyan-200">JSON</p><pre className="mt-3 text-[7px] leading-3 text-white/45">{`{\n  books: []\n}`}</pre></div></div>
      <div className="absolute bottom-5 left-5 right-5 flex justify-between text-[9px] uppercase tracking-[.2em] text-white/35"><span>Node.js</span><span>Validation</span><span>JSON output</span></div>
    </div>
  );

  return (
    <div className="relative h-64 overflow-hidden rounded-2xl border border-violet-300/20 bg-[radial-gradient(circle_at_50%_45%,rgba(124,58,237,.3),transparent_38%),linear-gradient(135deg,#09091b,#100724)] shadow-[0_24px_70px_rgba(124,58,237,.12)] transition duration-500 group-hover:-translate-y-1 group-hover:border-cyan-300/30">
      <div className="absolute inset-0 opacity-25" style={{ backgroundImage: "linear-gradient(rgba(139,92,246,.15) 1px,transparent 1px),linear-gradient(90deg,rgba(139,92,246,.15) 1px,transparent 1px)", backgroundSize: "28px 28px" }} />
      <div className="relative flex h-full items-center justify-center"><div className="absolute h-44 w-44 rounded-full bg-violet-600/20 blur-3xl" /><div className="relative flex h-24 w-24 items-center justify-center rounded-3xl border border-violet-300/40 bg-white/[.08] text-2xl font-semibold shadow-[0_0_50px_rgba(168,85,247,.25)] backdrop-blur">DA</div>{[["AI","left-8 top-10"],["CONTENT","right-7 top-8"],["SOFTWARE","left-6 bottom-9"],["DOMAINS","right-8 bottom-10"],["HOSTING","left-1/2 top-3"]].map(([label,pos]) => <span key={label} className={`absolute ${pos} rounded-full border border-white/10 bg-white/[.04] px-2.5 py-1 text-[7px] uppercase tracking-widest text-white/60 backdrop-blur`}>{label}</span>)}</div>
    </div>
  );
}

export default function Home() {
  return (
    <main className="min-h-screen overflow-hidden bg-[#030712] text-white selection:bg-violet-500/30">
      <section className="relative border-b border-white/[.07] bg-[radial-gradient(circle_at_78%_35%,rgba(37,99,235,.14),transparent_30%),radial-gradient(circle_at_96%_68%,rgba(124,58,237,.16),transparent_32%),#030712]">
        <div className="absolute inset-0 opacity-20" style={{ backgroundImage: "linear-gradient(rgba(255,255,255,.05) 1px,transparent 1px),linear-gradient(90deg,rgba(255,255,255,.05) 1px,transparent 1px)", backgroundSize: "48px 48px" }} />
        <div className="relative mx-auto max-w-6xl px-6 pb-20 pt-16 sm:pb-24 sm:pt-20">
          <div className="grid items-center gap-10 lg:grid-cols-[.9fr_1.1fr]">
            <div className="relative z-10">
              <div className="mb-5 inline-flex items-center gap-2 rounded-full border border-violet-400/25 bg-violet-500/[.07] px-3 py-1.5 text-[10px] font-medium uppercase tracking-[.2em] text-violet-200"><span className="h-1.5 w-1.5 rounded-full bg-cyan-300 shadow-[0_0_12px_rgba(103,232,249,.8)]" /> Backend AI Engineer</div>
              <h1 className="max-w-xl text-3xl font-semibold leading-none tracking-[-.04em] sm:text-5xl">LESLEI <span className="bg-gradient-to-r from-white via-cyan-100 to-violet-300 bg-clip-text text-transparent">MAKORI</span></h1>
              <p className="mt-6 max-w-xl text-lg leading-8 text-slate-300">I build, troubleshoot, and ship <span className="text-cyan-300">AI-powered web applications</span> that solve real business problems.</p>
              <div className="mt-7 flex flex-wrap gap-3"><Link href="/work" className="rounded-full bg-gradient-to-r from-cyan-400 to-violet-500 px-6 py-3 text-sm font-semibold shadow-[0_10px_35px_rgba(124,58,237,.24)] transition hover:-translate-y-0.5">View My Work →</Link><Link href="/about" className="rounded-full border border-white/20 bg-white/[.03] px-6 py-3 text-sm font-medium transition hover:border-cyan-300/50 hover:bg-white/[.06]">About Me</Link></div>
              <div className="mt-9 flex flex-wrap gap-2">{skills.map((skill) => <span key={skill} className="rounded-lg border border-white/10 bg-white/[.03] px-3 py-2 text-xs text-slate-300">{skill}</span>)}</div>
            </div>

            <div className="relative min-h-[400px] lg:min-h-[450px]">
              <div className="absolute -right-12 top-10 h-72 w-72 rounded-full bg-violet-600/15 blur-3xl" /><div className="absolute right-0 top-24 h-64 w-64 rounded-full bg-cyan-500/10 blur-3xl" />
              <div className="absolute left-[3%] top-[5%] w-[40%] -rotate-3 rounded-xl border border-cyan-300/20 bg-[#07101c]/90 p-4 shadow-2xl backdrop-blur-xl"><div className="flex gap-1.5"><span className="h-2 w-2 rounded-full bg-red-400/70" /><span className="h-2 w-2 rounded-full bg-yellow-300/70" /><span className="h-2 w-2 rounded-full bg-green-300/70" /></div><pre className="mt-4 text-[9px] leading-5 text-slate-400"><span className="text-emerald-300">const</span> solution = <span className="text-violet-300">build</span>();{`\n`}solution.<span className="text-cyan-300">debug</span>();{`\n`}solution.<span className="text-violet-300">ship</span>();</pre></div>
              <div className="absolute right-[1%] top-[10%] w-[67%] overflow-hidden rounded-2xl border border-blue-300/20 bg-[#08111f]/95 shadow-[0_30px_80px_rgba(37,99,235,.15)] backdrop-blur-xl"><div className="border-b border-white/10 px-3 py-2 text-[8px] text-white/45">LeadDesk / Dashboard</div><div className="grid grid-cols-4 gap-2 p-3">{[["Leads","248"],["Progress","92"],["Converted","56"],["Revenue","$24.8K"]].map(([a,b]) => <div key={a} className="rounded-lg border border-white/10 bg-white/[.03] p-2"><p className="text-[6px] text-white/35">{a}</p><p className="mt-1 text-sm font-semibold">{b}</p></div>)}</div><div className="mx-3 mb-3 h-20 rounded-lg border border-white/10 bg-white/[.025] p-3"><p className="text-[7px] text-white/35">Pipeline overview</p><div className="mt-5 h-1 rounded-full bg-gradient-to-r from-cyan-300 via-blue-400 to-violet-500" /></div></div>
              <div className="absolute bottom-[5%] left-[7%] w-[29%] rounded-full border border-violet-300/30 bg-[#080c19]/95 p-1.5 shadow-2xl backdrop-blur-xl"><div className="aspect-square overflow-hidden rounded-full border border-white/10 bg-white/[.04]"><img src="/leslei-makori.jpg" alt="Leslei Makori" className="h-full w-full object-cover object-center" /></div></div>
              <div className="absolute bottom-[8%] left-[30%] w-[40%] rounded-2xl border border-violet-300/20 bg-[#080c19]/95 p-3 shadow-2xl backdrop-blur-xl"><div className="flex items-center justify-between"><span className="text-[8px] uppercase tracking-widest text-violet-200">Build path</span><span className="text-[8px] text-white/30">01—04</span></div><div className="mt-3 flex items-center gap-2 text-[8px] text-white/50"><span className="rounded-full border border-white/10 px-2 py-1">Learn</span><span className="text-cyan-300">→</span><span className="rounded-full border border-white/10 px-2 py-1">Build</span><span className="text-cyan-300">→</span><span className="rounded-full border border-white/10 px-2 py-1">Debug</span><span className="text-violet-300">→</span><span className="rounded-full border border-white/10 px-2 py-1">Ship</span></div></div>
              <div className="absolute bottom-[8%] right-[0%] rounded-xl border border-cyan-300/20 bg-[#08111c]/95 px-3 py-2 shadow-2xl backdrop-blur-xl"><p className="text-[7px] uppercase tracking-widest text-cyan-200/70">Polite Scraper</p><p className="mt-1 font-mono text-[8px] text-white/45">web → JSON</p></div>
            </div>
          </div>
        </div>
      </section>

      <section className="border-b border-white/[.07] bg-[#050a14]"><div className="mx-auto max-w-6xl px-6 py-4"><div className="flex flex-wrap justify-center gap-x-10 gap-y-3 text-[9px] font-medium uppercase tracking-[.22em] text-slate-500"><span className="text-slate-300">JavaScript</span><span>TypeScript</span><span>Next.js</span><span>Node.js</span><span>Prisma</span><span>Neon</span><span>AI</span></div></div></section>

      <section className="mx-auto max-w-6xl px-6 py-20 sm:py-24"><div className="flex items-end justify-between gap-6"><div><p className="text-[10px] font-medium uppercase tracking-[.25em] text-violet-300">Selected Work</p><h2 className="mt-3 text-4xl font-semibold tracking-tight sm:text-5xl">Turning ideas into <span className="text-slate-500">real software.</span></h2></div><Link href="/work" className="hidden rounded-full border border-white/15 px-5 py-2.5 text-xs text-slate-300 hover:border-cyan-300/40 sm:block">View all projects →</Link></div><div className="mt-10 grid gap-6 lg:grid-cols-3">{projects.map((project,index) => <Link key={project.href} href={project.href} className="group rounded-2xl border border-white/10 bg-white/[.025] p-3 transition duration-500 hover:-translate-y-1 hover:border-violet-400/30 hover:bg-white/[.04]"><ProjectVisual index={index} /><div className="px-2 pb-3 pt-5"><div className="flex items-center justify-between"><span className="text-[9px] uppercase tracking-[.18em] text-slate-500">{project.number} · {project.status}</span><span className="text-violet-300 opacity-0 transition group-hover:opacity-100">↗</span></div><h3 className="mt-3 text-xl font-semibold">{project.title}</h3><p className="mt-2 text-sm leading-6 text-slate-400">{project.description}</p><div className="mt-4 flex flex-wrap gap-2">{project.tech.map((tech) => <span key={tech} className="rounded-full border border-white/10 px-2.5 py-1 text-[9px] text-slate-500">{tech}</span>)}</div></div></Link>)}</div></section>

      <section className="border-y border-white/[.07] bg-[radial-gradient(circle_at_15%_50%,rgba(37,99,235,.11),transparent_28%),radial-gradient(circle_at_85%_50%,rgba(124,58,237,.12),transparent_28%),#050a14]"><div className="mx-auto grid max-w-6xl gap-12 px-6 py-20 sm:py-24 lg:grid-cols-[1fr_.9fr] lg:items-center"><div><p className="text-[10px] uppercase tracking-[.25em] text-cyan-300">How I work</p><h2 className="mt-4 max-w-xl text-4xl font-semibold tracking-tight sm:text-5xl">The hard part is troubleshooting.</h2><p className="mt-6 max-w-xl leading-8 text-slate-400">Projects don&apos;t always work on the first attempt. I approach problems with patience, persistence, and commitment—keep testing, keep learning, and keep fixing.</p></div><div className="grid grid-cols-2 overflow-hidden rounded-2xl border border-white/10 bg-white/[.02]">{[["01","Learn"],["02","Build"],["03","Troubleshoot"],["04","Ship"]].map(([n,label],i) => <div key={n} className={`p-7 ${i < 2 ? "border-b" : ""} ${i % 2 === 0 ? "border-r" : ""} border-white/10`}><span className="text-3xl font-semibold">{n}</span><p className="mt-3 text-sm text-slate-500">{label}</p></div>)}</div></div></section>

      <section className="mx-auto max-w-6xl px-6 py-20 sm:py-24"><div className="rounded-3xl border border-white/10 bg-gradient-to-br from-white/[.04] to-violet-500/[.04] p-8 sm:p-12"><div className="flex flex-col gap-8 lg:flex-row lg:items-center lg:justify-between"><div><p className="text-[10px] uppercase tracking-[.25em] text-violet-300">Building toward what&apos;s next</p><h2 className="mt-3 text-3xl font-semibold sm:text-4xl">Becoming a stronger software + AI engineer.</h2><p className="mt-4 max-w-2xl text-sm leading-7 text-slate-400">I know enough to build. I&apos;m continuing to learn, troubleshoot, and build better.</p></div><div className="flex flex-wrap gap-3">{skills.slice(0,6).map((skill) => <span key={skill} className="rounded-full border border-white/10 bg-white/[.03] px-3 py-2 text-xs text-slate-400">{skill}</span>)}</div></div></div></section>

      <section className="border-t border-white/[.07]"><div className="mx-auto flex max-w-6xl flex-col gap-6 px-6 py-20 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-[10px] uppercase tracking-[.25em] text-slate-500">Have a project or idea?</p><h2 className="mt-3 text-3xl font-semibold sm:text-4xl">Let&apos;s build something useful.</h2></div><Link href="/contact" className="w-fit rounded-full bg-gradient-to-r from-cyan-400 to-violet-500 px-6 py-3 text-sm font-semibold shadow-[0_10px_35px_rgba(124,58,237,.22)] transition hover:-translate-y-0.5">Let&apos;s Work Together →</Link></div></section>
    </main>
  );
}
